version: 0.2

phases:
  preBuild:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: out # This is the default output directory for Next.js static exports
  files:
    - "**/*"
